language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: "test"
      script: ./mvnw clean test
    - stage: "install"
      script: ./mvnw clean install -Pstaging
    - stage: "deploy"
      before_install:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrus
      script: ./mvnw clean deploy --settings .maven.settings.xml -DskipTests=true -B -U -Prelease

stages:
  - test
  - name: install
    if: ((branch =~ /(master|release-\d+\.\d+\.x+)/) OR (type = pull_request))
  - name: deploy
    if: ((branch =~ /(master|release-\d+\.\d+\.x+)/) OR (type = pull_request))
