language: java
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.m2
install: true
script:
  -  ./mvnw clean install

# since tests are already executed during build
# so no need to run it again.
after_success:
  - ./mvnw jacoco:report coveralls:report

# only build master on direct commit to it
branches:
  only:
  - master
